language: go

os:
  - linux
  - osx

go:
  - 1.16.x
  - 1.x

matrix:
  exclude:
  - os: osx
    go: 1.16.x

install:
  - GO111MODULE=on go mod download
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./make.bash libax25; fi

script:
  - go vet ./...
  - ./make.bash
